stages:
  data_ingestion:
    cmd: python src/LangWizAI/pipeline/stage_01_data_ingestion.py
    deps:
      - src/LangWizAI/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data/europarl/processed
      - artifacts/data/wmt/processed