TrainingArguments:
    num_train_epochs: 3
    evaluation_strategy: "no"
    save_strategy: "epoch"
    learning_rate: 0.00002
    per_device_train_batch_size: 64
    per_device_eval_batch_size: 64
    weight_decay: 0.01
    save_total_limit: 3
    predict_with_generate: True
    fp16: False
    push_to_hub: False
    device: "mps"