artifacts_root: artifacts


europarl_data_ingestion:
  root_dir: artifacts/data/europarl/raw
  source_URL: https://www.statmt.org/europarl/v10/training/
  unzip_dir: artifacts/data/europarl/processed
  dataset_names:
    - europarl-v10.bg-en.tsv.gz
    - europarl-v10.cs-en.tsv.gz
    - europarl-v10.fr-en.tsv.gz

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt #gives if the model has the desired files or not
  ALL_REQUIRED_FILES: ['train', 'test','validation']

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data/europarl/processed/fr-en
  tokenizer_name: Helsinki-NLP/opus-mt-fr-en

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  data_path: artifacts/data_transformation/europarl/processed/fr_en
  model_ckpt: Helsinki-NLP/opus-mt-fr-en

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/europaarl/processed/fr-en
  model_path: artifacts/prepare_base_model/fr_en_model
  tokenizer_path: artifacts/prepare_base_model/fr_en_tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv
